// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic interface that matches our schema

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          username: string
          first_name: string
          last_name: string
          role: 'client' | 'admin'
          avatar: string | null
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          username: string
          first_name: string
          last_name: string
          role?: 'client' | 'admin'
          avatar?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          username?: string
          first_name?: string
          last_name?: string
          role?: 'client' | 'admin'
          avatar?: string | null
          created_at?: string
        }
      }
      clients: {
        Row: {
          id: number
          user_id: string
          coach_id: number | null
          height: number | null
          starting_weight: number | null
          goal_weight: number | null
          date_of_birth: string | null
        }
        Insert: {
          id?: number
          user_id: string
          coach_id?: number | null
          height?: number | null
          starting_weight?: number | null
          goal_weight?: number | null
          date_of_birth?: string | null
        }
        Update: {
          id?: number
          user_id?: string
          coach_id?: number | null
          height?: number | null
          starting_weight?: number | null
          goal_weight?: number | null
          date_of_birth?: string | null
        }
      }
      exercises: {
        Row: {
          id: number
          name: string
          description: string | null
          instructions: string | null
          muscle_groups: string[] | null
          equipment: string | null
          difficulty_level: 'beginner' | 'intermediate' | 'advanced' | null
          video_url: string | null
          thumbnail_url: string | null
          created_by: string | null
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          name: string
          description?: string | null
          instructions?: string | null
          muscle_groups?: string[] | null
          equipment?: string | null
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | null
          video_url?: string | null
          thumbnail_url?: string | null
          created_by?: string | null
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          description?: string | null
          instructions?: string | null
          muscle_groups?: string[] | null
          equipment?: string | null
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | null
          video_url?: string | null
          thumbnail_url?: string | null
          created_by?: string | null
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      programs: {
        Row: {
          id: number
          coach_id: string
          name: string
          description: string | null
          duration_weeks: number | null
          difficulty_level: 'beginner' | 'intermediate' | 'advanced' | null
          program_type: 'strength' | 'cardio' | 'hybrid' | 'flexibility' | 'sports_specific' | null
          is_template: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          coach_id: string
          name: string
          description?: string | null
          duration_weeks?: number | null
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | null
          program_type?: 'strength' | 'cardio' | 'hybrid' | 'flexibility' | 'sports_specific' | null
          is_template?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          coach_id?: string
          name?: string
          description?: string | null
          duration_weeks?: number | null
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | null
          program_type?: 'strength' | 'cardio' | 'hybrid' | 'flexibility' | 'sports_specific' | null
          is_template?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      workouts: {
        Row: {
          id: number
          program_id: number | null
          name: string
          description: string | null
          day_number: number | null
          week_number: number | null
          estimated_duration: number | null
          instructions: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          program_id?: number | null
          name: string
          description?: string | null
          day_number?: number | null
          week_number?: number | null
          estimated_duration?: number | null
          instructions?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          program_id?: number | null
          name?: string
          description?: string | null
          day_number?: number | null
          week_number?: number | null
          estimated_duration?: number | null
          instructions?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: number
          sender_id: string
          recipient_id: string
          content: string
          message_type: 'text' | 'image' | 'video' | 'workout' | 'meal_plan'
          attachment_url: string | null
          workout_id: number | null
          meal_plan_id: number | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: number
          sender_id: string
          recipient_id: string
          content: string
          message_type?: 'text' | 'image' | 'video' | 'workout' | 'meal_plan'
          attachment_url?: string | null
          workout_id?: number | null
          meal_plan_id?: number | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: number
          sender_id?: string
          recipient_id?: string
          content?: string
          message_type?: 'text' | 'image' | 'video' | 'workout' | 'meal_plan'
          attachment_url?: string | null
          workout_id?: number | null
          meal_plan_id?: number | null
          is_read?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      difficulty_level: 'beginner' | 'intermediate' | 'advanced'
      program_type: 'strength' | 'cardio' | 'hybrid' | 'flexibility' | 'sports_specific'
      message_type: 'text' | 'image' | 'video' | 'workout' | 'meal_plan'
    }
  }
}
